<?php

namespace FB\groupeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Membre_GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Membre_GroupeRepository extends EntityRepository
{
}
