f_bgroupe_accueil:
    pattern:  /
    defaults: { _controller: FBgroupeBundle:Accueil:index }
    
_security_check:
  pattern:  /Init_Groupes
  defaults: { _controller: FBgroupeBundle:Accueil:login_reussi }
  requirements:
f_bgroupe_getFormGroup:
    pattern:  /Init_Groupes/formGroup
    defaults: { _controller: FBgroupeBundle:Accueil:getFormGroup}
    
f_bgroupe_ajouterGroup:
    pattern:  /Init_Groupes/ajouterGroup
    defaults: { _controller: FBgroupeBundle:Accueil:ajouterGroup}
    
_security_logout:
  pattern:  /logout
  defaults: { _controller: FBgroupeBundle:Accueil:deconnecte}