f_bgroupe_accueil:
    pattern:  /
    defaults: { _controller: FBgroupeBundle:Accueil:index }
    
_security_check:
  pattern:  /Init_Groupes
  defaults: { _controller: FBgroupeBundle:Accueil:login_reussi }
  
  
f_bgroupe_getFormGroup:
    pattern:  /Init_Groupes/formGroup
    defaults: { _controller: FBgroupeBundle:Accueil:getFormGroup}
    
f_bgroupe_ajouterGroup:
    pattern:  /Init_Groupes/ajouterGroup
    defaults: { _controller: FBgroupeBundle:Accueil:ajouterGroup}
f_bgroupe_supprimerGroup:
    pattern: /Init_Groupes/suppGrp/{idgp}
    defaults: {_controller: FBgroupeBundle:Accueil:supprimerGroup,_format: json}
FB_importMb:
    pattern : /Init_Groupes/importMembre
    defaults: {_controller: FBgroupeBundle:Accueil:supprimerGroup,_format: json}
    
_security_logout:
  pattern:  /logout
  defaults: { _controller: FBgroupeBundle:Accueil:deconnecte}

f_bgroupe_getObjet: 
               pattern: /donnes/{id}&{entite}
               defaults: { _controller: FBgroupeBundle:Accueil:getObjet, _format: json}
