<?php

namespace Proxies\__CG__\FB\groupeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Utilisateur extends \FB\groupeBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setSexe($sexe)
    {
        $this->__load();
        return parent::setSexe($sexe);
    }

    public function getSexe()
    {
        $this->__load();
        return parent::getSexe();
    }

    public function getGroupes()
    {
        $this->__load();
        return parent::getGroupes();
    }

    public function getPosts()
    {
        $this->__load();
        return parent::getPosts();
    }

    public function getCommentaires()
    {
        $this->__load();
        return parent::getCommentaires();
    }

    public function addPost(\FB\groupeBundle\Entity\Post $posts)
    {
        $this->__load();
        return parent::addPost($posts);
    }

    public function removePost(\FB\groupeBundle\Entity\Post $posts)
    {
        $this->__load();
        return parent::removePost($posts);
    }

    public function addGroupe(\FB\groupeBundle\Entity\MembreGroupe $groupe)
    {
        $this->__load();
        return parent::addGroupe($groupe);
    }

    public function removeGroupe(\FB\groupeBundle\Entity\MembreGroupe $groupe)
    {
        $this->__load();
        return parent::removeGroupe($groupe);
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setNomEntier($nomEntier)
    {
        $this->__load();
        return parent::setNomEntier($nomEntier);
    }

    public function getNomEntier()
    {
        $this->__load();
        return parent::getNomEntier();
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'nomEntier', 'nom', 'prenom', 'email', 'sexe', 'groupes', 'posts');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}